version: '3.9'
services:
  readme.blog.mongo:
    image: mongo:4.4
    restart: always
    container_name: readme.blog.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - ${MONGO_PORT}:27017

    volumes:
      - readme.mongo.blog:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/readme-blog --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  readme.blog.mongo.ui:
    image: mongo-express
    restart: always
    container_name: readme.blog.mongo.ui
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@readme.blog.mongo:27017/

volumes:
  readme.mongo.blog: